catalog/urls.py
from django.urls import include
from django.urls import path
from . import views
urlpatterns = [
    path('',views.index,name='home'),
    path('books/',views.BookListView.as_view(),name='books'),
    path('book/<int:pk>',views.BookDetailView.as_view(),name='book-detail'),
    path('authors/',views.AuthorListView.as_view(),name='authors'),
    path('author/<int:pk>',views.author_detail_view,name='author-detail'),
]

library/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import RedirectView

# for static
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('test/', views.test,name='test' ),
    path('catalog/',include('catalog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('',RedirectView.as_view(url='catalog/')),
]+static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)


#     path('accounts/login/', name='login'),
#     path('accounts/logout/', name='logout'),
#     path('accounts/password_change/', name='password_change'),
#     path('accounts/password_change/done/', name='password_change_done'),
#     path('accounts/password_reset/', name='password_reset'),
#     path('accounts/password_reset/done/', name='password_reset_done'),

catalog/models.py
from django.db import models
from django.urls import reverse
import uuid

# Create your models here.

class Genre(models.Model):
    name = models.CharField(max_length=200,help_text="Enter a book genre(e.g. Science Fiction)")
    
    def __str__(self):
        return self.name 



class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)
    
    class Meta:
        ordering=['last_name','first_name']
    
    def get_absolute_url(self):
        return reverse('author-detail',args=[str(self.id)])
    
    def show_all_books(self):
        return ', '.join(book.title for book in self.book_set.all()[:3])
    # self.book_set.all() ///  book is Model name ,, book_set in geting value for many to many relation which relation declare from another Model
    
    
    def __str__(self):
        return f'{self.first_name},{self.last_name}'
       

class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.ManyToManyField('Author')
    language = models.ForeignKey('Language',on_delete=models.SET_NULL,null=True)
    summery = models.TextField(help_text='Enter a brief description of the book')
    isbn = models.CharField('ISBN', max_length=13, help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    genre = models.ManyToManyField(Genre,help_text='Select a genre for this book')
    book_added_date = models.DateTimeField(auto_now_add=True)

    
    def get_absolute_url(self):
        return reverse('book-detail',args=[str(self.id)])
    
    def display_genre(self):
        return ', '.join(genre.name for genre in self.genre.all()[:3])
    
    display_genre.short_description = 'Genre'
    
    def show_author(self):
        return ' '.join(author.first_name for author in self.author.all()[:3])
    show_author.short_description = 'Author'
    
    def __str__(self):
        return f'{self.title}'


from datetime import date

from django.contrib.auth.models import User

class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True,default=uuid.uuid4,help_text='Unique Id for this particular book for whole library')
    book = models.ForeignKey('Book',on_delete=models.SET_NULL,null=True)
    imprint = models.CharField(max_length=200)
    book_borrow_date = models.DateTimeField(auto_now_add=True)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User,on_delete=models.SET_NULL,null=True,blank=True)
    
    @property
    def is_overdue(self):
        if self.due_back and date.today()> due_back:
            return True
        return False
        
     
    LOAN_STATUS = (
        ('m','Maintenance'),
        ('o','On loan'),
        ('a','Available'),
        ('r','Reserved')
    )
    
    
    status = models.CharField(
        max_length=1,
        choices = LOAN_STATUS,
        blank= True,
        default= 'm',
        help_text='Book Availability'
        
    )
    
    class Meta:
        ordering=['due_back']
        permissions = (("can_mark_returned", "Set book as returned"),)

    
    def __str__(self):
        return f'{self.id} ({self.book.title})'  


class Language(models.Model):
    language_name = models.CharField(max_length=150)
    
    def __str__(self):
        return f'{self.language_name}'

catalog/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.

# default 
from datetime import date,timedelta
from django.views.generic import ListView,DetailView

#custom
from .models import Book,BookInstance,Author,Genre

start_date = date.today()
end_date_week_difference = start_date + timedelta(days=6)

def index(request):
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    num_book_instance_available = BookInstance.objects.filter(status__exact='a').count()
    num_authors = Author.objects.all().count()
    num_genres = Genre.objects.all().count()
    all_books = Book.objects.order_by('-book_added_date')[:6]
    
    num_visits = request.session.get('num_visits',0)
    request.session['num_visits'] = num_visits + 1
    
    context = {
        'num_books':num_books,
        'num_instances':num_instances,
        'num_book_instance_available':num_book_instance_available,
        'num_authors':num_authors,
        'num_genres':num_genres,
        'all_books':all_books,
        'num_visits':num_visits,
    }
    
    return render(request,'index.html',context=context)


class BookListView(ListView):
    model = Book
    context_object_name = 'my_book_list'
    template_name = 'books/book_list.html'
    paginate_by = 8
    
    def get_queryset(self):
        return Book.objects.order_by('-book_added_date')[:6]
    def get_context_data(self, **kwargs):
        context = super(BookListView, self).get_context_data(**kwargs)
        context['authors'] = 'This is just some data'
        return context
    
    
class BookDetailView(DetailView):
    model = Book
    template_name = 'books/book_details.html'
    

class AuthorListView(ListView):
     model = Author
     template_name = 'books/author_list.html'
     context_object_name = 'author_list'
     
     def get_queryset(self):
          return Author.objects.order_by('first_name')
    

from django.shortcuts import get_object_or_404

def author_detail_view(request,pk):
    author= get_object_or_404(Author,pk=pk)
    return render(request,'books/author_detail.html',context={'author':author})
    
    

library/views.py
from django.shortcuts import render

def test(request):
    return render(request,'test.html')

catalog/templates/base_generic.html
<!DOCTYPE html>

{% load static %}

<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>{% block title %} Tarunno Public Library {% endblock %}</title>

  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>


  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/simple-sidebar.css' %}" rel="stylesheet">

  <link rel="stylesheet" href="{% static 'css/new.css' %}">

  
    <!-- Bootstrap 4 -->
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
        integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
        integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
        integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous">
    </script> -->

    <!-- Font Awesome -->
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
        integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    <!-- Moment.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.23.0/moment.min.js"
        integrity="sha256-VBLiveTKyUZMEzJd6z2mhfxIqz3ZATCuVMawPZGzIfA=" crossorigin="anonymous"></script>

    <!-- Tempus Dominus Bootstrap 4 -->
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/css/tempusdominus-bootstrap-4.min.css"
        integrity="sha256-XPTBwC3SBoWHSmKasAk01c08M6sIA5gF5+sRxqak2Qs=" crossorigin="anonymous" />
    <script
        src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/js/tempusdominus-bootstrap-4.min.js"
        integrity="sha256-z0oKYg6xiLq3yJGsp/LsY9XykbweQlHl42jHv2XTBz4=" crossorigin="anonymous"></script>


</head>

<body>

  <div class="d-flex toggled" id="wrapper">

    <!-- Sidebar -->
    <div class="bg-dark border-right" id="sidebar-wrapper">
      <div class="sidebar-heading text-warning text-center">  <strong> Tarunno Library</strong> </div>
      <div class="list-group list-group-flush">

        <div class="sidebar sidebar-content">
            <div class="sidebar-category sidebar-default sidebar-content ">
                <div class="sidebar-user">
                    <div class="category-content">
                        <h6>Jubel Ahmed</h6>
                        <small>Chairmen</small>
                    </div>
                </div>
            </div>
            <!-- /Sidebar Category -->
            
            <div class="sidebar-category sidebar-content sidebar-default  bg-white">

                <div class="category-title">
                    <span>Books</span>
                </div>
                <div class="category-content">
                    <ul id="fruits-nav" class="nav flex-column">
                        <li class="nav-item">
                            <a href="{% url 'books' %}" class="nav-link">
                                <i class="fa fa-pencil" aria-hidden="true"></i>
                                All Books
                            </a>
                        </li>

                        {% if user.is_authenticated %}

                            <li class="nav-item">
                                <a href="#" class="nav-link">
                                    <i class="fa fa-pencil" aria-hidden="true"></i>
                                    Borrow Books
                                </a>
                            </li>
                        {% endif %}

                        <li class="nav-item">
                            <a href="#other-fruits" class="nav-link" data-toggle="collapse" role="button"
                                aria-expanded="false" aria-controls="other-fruits">
                                <i class="fa fa-pencil" aria-hidden="true"></i>
                                Catagory
                            </a>
                            <ul id="other-fruits" class="flex-column collapse">
                                <li class="nav-item">
                                    <a href="#" class="nav-link">
                                        <i class="fa fa-pencil" aria-hidden="true"></i>
                                        Fiction
                                    </a>
                                </li>
                                <li class="nav-item ">
                                    <a href="#" class="nav-link">
                                        <i class="fa fa-pencil" aria-hidden="true"></i>
                                        Story
                                    </a>
                                </li>
                            </ul>
                            <!-- /Sub Nav -->
                        </li>
                    </ul>
                    <!-- /Nav -->
                </div>
                <!-- /Category Content -->
            </div>
            <!-- /Sidebar Category -->
            <div class="sidebar-category sidebar-default  bg-white">
                <div class="category-title">
                    <span>Author</span>
                </div>
                <div class="category-content">
                    <ul id="sidebar-editable-nav" class="nav flex-column">
                        <li class="nav-item">
                            <a href="{%url 'authors' %}" class="nav-link">
                                <i class="fa fa-pencil" aria-hidden="true"></i>
                                All authors
                            </a>
                        </li>

                    </ul>
                    <!-- /Nav -->
                </div>
                <!-- /Category Content -->
            </div>
            <!-- /Sidebar Category -->
        </div>
      </div>
    </div>
    <!-- /#sidebar-wrapper -->

    <!-- Page Content -->
    <div id="page-content-wrapper" >

      <nav class="navbar navbar-expand-lg navbar-light bg-dark text-white border-bottom fixed-top ">
        <button class="btn btn-dark" id="menu-toggle"> <i class="fa fa-bars"></i> </button>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse " id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto  mt-2 mt-lg-0 ">
            <li class="nav-item active">
                <span>
                    <a class="nav-link text-warning" href="{% url 'home' %}"> <i class="fa fa-home" aria-hidden="true"></i> <strong> Home</strong></a>
                </span>
            </li>
            
            {% if user.is_authenticated %}

            
                <li class="nav-item">
                    <a class="nav-link text-danger " href="{% url 'logout' %}"> <i class="fa fa-pencil"></i> Log Out </a>
                </li>
                <!-- <li class="nav-item ">
                <span class="navbar-text text-info" >{{ user.username }}</span>
                </li> -->
  
            {% else %}
                <li class="nav-item">
                    <span>
                        <a class="nav-link text-danger" href="{% url 'login' %}"> <i class="fa fa-pencil" aria-hidden="true"></i> <strong> Login</strong></a>
                    </span>
                </li>
  
            {% endif %}
            
          </ul>
        </div>
      </nav>

      <div class="container-fluid " style="padding-top: 3.5rem;">

        {% block content %}
            content
        {% endblock %}
        {% block pagination %}
        {% if is_paginated %}
        <div class="pagination m-5">
            <span class="page-links">
                {% if page_obj.has_previous %}
                <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
        {% endif %}
        {% endblock pagination %}
      </div>
    </div>
    <!-- /#page-content-wrapper -->

  </div>
  <!-- /#wrapper -->

  <!-- Bootstrap core JavaScript -->
  
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'js/new.js' %}"></script>

  <!-- Menu Toggle Script -->
  <script>
    $("#menu-toggle").click(function(e) {
      e.preventDefault();
      $("#wrapper").toggleClass("toggled");
    });
  </script>

</body>

</html>

catalog/templates/books/author_detail.html
{% extends 'base_generic.html' %}
{% load static %}
{% block title %} Author Details {% endblock %}

{% block content %}

<div class="row ">
    <div class="col-sm-6 bg-">
        <div class="card mt-2" style="width:18rem;  border:none">
            <div class="card-body">
              <h5 class="card-title">{{author.first_name}} {{author.last_name}}</h5>
              <p class="card-text">Birth Date : {{author.date_of_birth}}</p>
              {% if author.date_of_died %}
              <p class="card-text">Died Date : {{author.date_of_died}}</p>
              {% endif %}
              <button class="btn p-0">
                      Books <span class="p-2 badge badge-primary">{{author.book_set.all.count}}</span>
              </button>
              <!-- <a href="#" class="btn btn-primary">Go somewhere</a> -->
            </div>
          </div>
    </div>
    <div class="col-sm-4 m-4">
        <img class="card-img-top"  src="{% static 'img/book_cover.png' %}" alt="Card image cap">
    </div>
</div>
<div class="row ">
    <div class="col-sm-12">
        
            <h5 class="text-secondary p-3">Books</h5>
        
        
        <ul class="list-group list-group-flush">
            {% for book in author.book_set.all %}
            <li class="list-group-item">
                <h5> <a href="{{book.get_absolute_url}}">{{book.title}}</a> </h5>
                <p>{{book.summery}}</p>
            
            </li>
            {% endfor %}
            
            </ul>
            
    </div>
   
    
</div>



{% endblock %}

catalog/templates/books/author_list.html
{% extends 'base_generic.html' %}
{% load static %}
{% block title %} Author List {% endblock %}

{% block content %}
 
    <div class="m-2 row justify-content-center">
        <div class="col-sm-3 bg-danger" ><h5 class="p-2 text-info text-center ">All Authors</h5></div>
    </div>

    <table class="table">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Author Name</th>
            <th scope="col">Birth Date</th>
            <th scope="col">Number of Books</th>
            <th scope="col">Books list</th>
            <!-- <th scope="col">Handle</th> -->
          </tr>
        </thead>
        <tbody>
  {% if author_list %}
  
    {% for author in author_list %}

          <tr>
            <td> <a href="{{ author.get_absolute_url }}">{{ author.first_name }} {{author.last_name }}</a>  </td>
            <td>({{author.date_of_birth}})</td>
            <td>{{author.book_set.all.count}}</td>
            <td>{{author.show_all_books}}</td>
            
          </tr>
       
      
      
    {% endfor %}
      
</tbody>
</table>

  {% else %}
    <p>There have no author .</p>
  {% endif %}       
{% endblock %}

catalog/templates/books/book_details.html
{% extends 'base_generic.html' %}
{% load static %}
{% block title %} Books Details {% endblock %}

{% block content %}

<div class="jumbotron">
    <h1 class="display-6 text-primary">{{ book.title }}</h1>
    <p class=""><strong class="text-info">Author:</strong>
        {% for author in book.author.all %}
        <a class="text-info" href="{{ author.get_absolute_url }}">{{ author.first_name }} {{author.last_name}} 
            {% if book.author.all.count > 1 %}
            <span class="text-primary">|</span>
            {% endif %}
        </a>
        {% endfor %}

    </p>
    <hr class="my-4">
    <div class="text-secondary">
        <p><strong>Summary:</strong> {{ book.summery }}</p>

    <p><strong>ISBN:</strong> {{ book.isbn }}</p>
    <p><strong>Language:</strong> {{ book.language }}</p>
    <p><strong>Genre:</strong> {{ book.genre.all|join:", " }}</p>

    </div>
    <div  style="margin-left:15px;margin-top:20px">
        {%if book.bookinstance_set.all %}
        <h4 class="text-info">Copies</h4>

        {% for copy in book.bookinstance_set.all %}
        <hr>
        <p
            class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
            {{ copy.get_status_display }}
        </p>
        {% if copy.status != 'a' %}
        <p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>
        {% endif %}
        <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
        <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
        {% endfor %}
        {%endif%}
    </div>
</div>


{% endblock %}

catalog/templates/books/book_list.html
{% extends 'base_generic.html' %}
{% load static %}
{% block title %} Books List {% endblock %}

{% block content %}

<div class="container">
    {% if my_book_list %}
    <h5 class="display-6 text-info pl-3 pt-3 "> <strong>All Books</strong> </h5>
<div class="d-flex flex-row flex-wrap mb-4">
    
    {% for book in my_book_list %}

    <div class="">
        <div class="card m-2 " style="width: 18rem;">
            <img class="card-img-top" src="{% static 'img/book_cover.png' %}" alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title"><a href="{{ book.get_absolute_url }}">{{ book.title }}</a></h5>
                <p class="card-text">{{book.summery}}</p>
                <h6 class="card-title ">
                    {% for author in book.author.all %}
                    <a class="text-warning" href="{{ author.get_absolute_url }}">{{ author.first_name }}
                    {% if book.author.all.count > 1 %}
                    <span class="text-primary">|</span>  
                    {% endif %}  
                    </a>
                    {% endfor %}
                </a></h6>
            </div>
        </div>
    </div>

    {% endfor %}
</div>
{% else %}
<p class="m-5">There are no books in the library.</p>
{% endif %}
</div>

{% endblock %}

catalog/templates/index.html
{% extends 'base_generic.html' %}
{% load static %}
{% block title %} Library Home {% endblock %}

{% block content %}

<div >
   <div class="row bg-dark mb-3 justify-content-center ">

      <div class="col-sm-12 col-md-6 col-lg-6 ">
         <blockquote class="pt-2 blockquote text-center " style=" border-radius: 25px;">
            <h2 class="text-danger " style="padding-top: 1.3rem;">তারুণ্য পাবলিক লাইব্রেরি</h2>
            <footer class="blockquote-footer text-center text-light bg-dark pb-2">( পরিচালনায় : তারুণ্য
               সমাজকল্যাণ পরিষদ ) </footer>
         </blockquote>
   
   
      </div>
   
   
   
   </div>
   
   <div class="row ">
   
      <div class="col-sm-12 col-md-9 col-lg-9">
   
         <div class="row">
            <div class="col-sm-12 col-md-4 col-lg-4">
               <div class=" mb-2 card text-center bg-info">
                  <div class="card-header text-white">
                     <strong> Recent added books</strong>
                  </div>
               </div>
            </div>
   
         </div>
   
   
         <div class="row">
   
            {% if all_books %}
   
            {% for book in all_books %}
            <div class="col-sm-10 col-md-6 col-lg-4 mb-2 ">
               <div class="card" style="width: 100%;">
                  <img class="card-img-top" src="{% static 'img/book_cover.png' %}" alt="Cover Page">
                  <div class="card-body">
                     <h5 class="card-title"> {{book.title}}</h5>
                     <h6 class="card-subtitle mb-2 text-muted">{{book.show_author}}</h6>
                     <p class="card-text">{{book.summery}}</p>
                     <a href="{{ book.get_absolute_url }}" class="card-link " style="float: right;">Details</a>
   
                  </div>
               </div>
            </div>
   
            {% endfor %}
            <div class="col-sm-12">
               <button style="float: right;" class="btn m-2"><a href="{% url 'books' %}">Show All Books</a></button>
            </div>
            {% else %}
            <p class="pl-3 py-5">There are no books in the library.</p>
            {% endif %}

            
   
         </div>
   
      </div>
   
   
      <div class="col-sm-12 col-md-3 col-lg-3">
         <div class="card" >
            <div class="card-header bg-info text-white">
               <strong> Library Records </strong>
            </div>
            <ul class="list-group list-group-flush">
               <li class="list-group-item text-primary">
                  Books <span class="badge badge-info p-2">{{ num_books }} </span>
               </li>
               <li class="list-group-item text-primary">
                  Copies <span class="badge badge-info p-2">{{ num_instances }} </span>
               </li>
               <li class="list-group-item text-primary">
                  Copies available <span class="badge badge-info p-2">{{num_book_instance_available }} </span>
               </li>
               <li class="list-group-item text-primary">
                  Authors <span class="badge badge-info p-2">{{ num_authors }} </span>
               </li>
               <li class="list-group-item text-primary">
                  Genres <span class="badge badge-info p-2">{{ num_genres }} </span>
               </li>
   
            </ul>
         </div>
      </div>

      <div class="col-sm-12">
         <div class="mt-3 ml-3 mb-3">
            <p>You have visited this page {{ num_visits }}{% if num_visits == 1 %} time{% else %} times{% endif %}.</p>

         </div>
      </div>

   </div>
</div>

{% endblock %}

templates/test.html
<!DOCTYPE html>

{% load static %}

<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Simple Sidebar - Start Bootstrap Template</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/simple-sidebar.css' %}" rel="stylesheet">

</head>

<body>

  <div class="d-flex toggled" id="wrapper">

    <!-- Sidebar -->
    <div class="bg-light border-right" id="sidebar-wrapper">
      <div class="sidebar-heading">Start Bootstrap </div>
      <div class="list-group list-group-flush">
        <a href="#" class="list-group-item list-group-item-action bg-light">Dashboard</a>
        <a href="#" class="list-group-item list-group-item-action bg-light">Shortcuts</a>
        <a href="#" class="list-group-item list-group-item-action bg-light">Overview</a>
        <a href="#" class="list-group-item list-group-item-action bg-light">Events</a>
        <a href="#" class="list-group-item list-group-item-action bg-light">Profile</a>
        <a href="#" class="list-group-item list-group-item-action bg-light">Status</a>
      </div>
    </div>
    <!-- /#sidebar-wrapper -->

    <!-- Page Content -->
    <div id="page-content-wrapper">

      <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
        <button class="btn btn-primary" id="menu-toggle">Toggle Menu</button>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Dropdown
              </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </li>
          </ul>
        </div>
      </nav>

      <div class="container-fluid">
        <h1 class="mt-4">Simple Sidebar</h1>
        <p>The starting state of the menu will appear collapsed on smaller screens, and will appear non-collapsed on larger screens. When toggled using the button below, the menu will change.</p>
        <p>Make sure to keep all page content within the <code>#page-content-wrapper</code>. The top navbar is optional, and just for demonstration. Just create an element with the <code>#menu-toggle</code> ID which will toggle the menu when clicked.</p>
      </div>
    </div>
    <!-- /#page-content-wrapper -->

  </div>
  <!-- /#wrapper -->

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Menu Toggle Script -->
  <script>
    $("#menu-toggle").click(function(e) {
      e.preventDefault();
      $("#wrapper").toggleClass("toggled");
    });
  </script>

</body>

</html>